services:
  app:
    build: 
      context: .
      target: development
    command: ["bash", "./start.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./storage:/storage
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - __pycache__/
        - action: sync
          path: ./requirements.txt
          target: /app/requirements.txt
        - action: rebuild
          path: ./Dockerfile

  celery:
    build: .
    command: >
      watchfiles --filter python "celery -A app.config.worker worker --loglevel=debug --pool=solo --purge" /app
    volumes:
      - .:/app
      - ./storage:/storage
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app
      - C_FORCE_ROOT=true
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - app-network
    restart: always

  celery-beat:
    build: .
    command: celery -A app.config.worker beat --loglevel=info
    volumes:
      - .:/app
      - ./storage:/storage
      - celerybeat-data:/app/celerybeat-data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}


    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network

volumes:
  mysql_data:
  celerybeat-data:

networks:
  app-network:
    driver: bridge
