from app.modules.countries.models.country_model import Country
from sqlalchemy.orm import Session

class CountrySeeder:
    
    @staticmethod
    def run(db: Session):
        countries = [
            { "name": "Afganistán", "iso2": "AF", "iso3": "AFG" },
            { "name": "Albania", "iso2": "AL", "iso3": "ALB" },
            { "name": "Argelia", "iso2": "DZ", "iso3": "DZA" },
            { "name": "Andorra", "iso2": "AD", "iso3": "AND" },
            { "name": "Angola", "iso2": "AO", "iso3": "AGO" },
            { "name": "Antigua y Barbuda", "iso2": "AG", "iso3": "ATG" },
            { "name": "Argentina", "iso2": "AR", "iso3": "ARG" },
            { "name": "Armenia", "iso2": "AM", "iso3": "ARM" },
            { "name": "Australia", "iso2": "AU", "iso3": "AUS" },
            { "name": "Austria", "iso2": "AT", "iso3": "AUT" },
            { "name": "Azerbaiyán", "iso2": "AZ", "iso3": "AZE" },
            { "name": "Bahamas", "iso2": "BS", "iso3": "BHS" },
            { "name": "Baréin", "iso2": "BH", "iso3": "BHR" },
            { "name": "Bangladés", "iso2": "BD", "iso3": "BGD" },
            { "name": "Barbados", "iso2": "BB", "iso3": "BRB" },
            { "name": "Bielorrusia", "iso2": "BY", "iso3": "BLR" },
            { "name": "Bélgica", "iso2": "BE", "iso3": "BEL" },
            { "name": "Belice", "iso2": "BZ", "iso3": "BLZ" },
            { "name": "Benín", "iso2": "BJ", "iso3": "BEN" },
            { "name": "Bután", "iso2": "BT", "iso3": "BTN" },
            { "name": "Bolivia", "iso2": "BO", "iso3": "BOL" },
            { "name": "Bosnia y Herzegovina", "iso2": "BA", "iso3": "BIH" },
            { "name": "Botsuana", "iso2": "BW", "iso3": "BWA" },
            { "name": "Brasil", "iso2": "BR", "iso3": "BRA" },
            { "name": "Brunéi", "iso2": "BN", "iso3": "BRN" },
            { "name": "Bulgaria", "iso2": "BG", "iso3": "BGR" },
            { "name": "Burkina Faso", "iso2": "BF", "iso3": "BFA" },
            { "name": "Burundi", "iso2": "BI", "iso3": "BDI" },
            { "name": "Cabo Verde", "iso2": "CV", "iso3": "CPV" },
            { "name": "Camboya", "iso2": "KH", "iso3": "KHM" },
            { "name": "Camerún", "iso2": "CM", "iso3": "CMR" },
            { "name": "Canadá", "iso2": "CA", "iso3": "CAN" },
            { "name": "Chad", "iso2": "TD", "iso3": "TCD" },
            { "name": "Chile", "iso2": "CL", "iso3": "CHL" },
            { "name": "China", "iso2": "CN", "iso3": "CHN" },
            { "name": "Chipre", "iso2": "CY", "iso3": "CYP" },
            { "name": "Colombia", "iso2": "CO", "iso3": "COL" },
            { "name": "Comoras", "iso2": "KM", "iso3": "COM" },
            { "name": "Congo (Brazzaville)", "iso2": "CG", "iso3": "COG" },
            { "name": "Congo (Kinshasa)", "iso2": "CD", "iso3": "COD" },
            { "name": "Corea del Norte", "iso2": "KP", "iso3": "PRK" },
            { "name": "Corea del Sur", "iso2": "KR", "iso3": "KOR" },
            { "name": "Costa de Marfil", "iso2": "CI", "iso3": "CIV" },
            { "name": "Costa Rica", "iso2": "CR", "iso3": "CRI" },
            { "name": "Croacia", "iso2": "HR", "iso3": "HRV" },
            { "name": "Cuba", "iso2": "CU", "iso3": "CUB" },
            { "name": "Dinamarca", "iso2": "DK", "iso3": "DNK" },
            { "name": "Dominica", "iso2": "DM", "iso3": "DMA" },
            { "name": "Ecuador", "iso2": "EC", "iso3": "ECU" },
            { "name": "Egipto", "iso2": "EG", "iso3": "EGY" },
            { "name": "El Salvador", "iso2": "SV", "iso3": "SLV" },
            { "name": "Emiratos Árabes Unidos", "iso2": "AE", "iso3": "ARE" },
            { "name": "Eritrea", "iso2": "ER", "iso3": "ERI" },
            { "name": "Eslovaquia", "iso2": "SK", "iso3": "SVK" },
            { "name": "Eslovenia", "iso2": "SI", "iso3": "SVN" },
            { "name": "España", "iso2": "ES", "iso3": "ESP" },
            { "name": "Estados Unidos", "iso2": "US", "iso3": "USA" },
            { "name": "Estonia", "iso2": "EE", "iso3": "EST" },
            { "name": "Esuatini", "iso2": "SZ", "iso3": "SWZ" },
            { "name": "Etiopía", "iso2": "ET", "iso3": "ETH" },
            { "name": "Fiyi", "iso2": "FJ", "iso3": "FJI" },
            { "name": "Filipinas", "iso2": "PH", "iso3": "PHL" },
            { "name": "Finlandia", "iso2": "FI", "iso3": "FIN" },
            { "name": "Francia", "iso2": "FR", "iso3": "FRA" },
            { "name": "Gabón", "iso2": "GA", "iso3": "GAB" },
            { "name": "Gambia", "iso2": "GM", "iso3": "GMB" },
            { "name": "Georgia", "iso2": "GE", "iso3": "GEO" },
            { "name": "Ghana", "iso2": "GH", "iso3": "GHA" },
            { "name": "Granada", "iso2": "GD", "iso3": "GRD" },
            { "name": "Grecia", "iso2": "GR", "iso3": "GRC" },
            { "name": "Guatemala", "iso2": "GT", "iso3": "GTM" },
            { "name": "Guinea", "iso2": "GN", "iso3": "GIN" },
            { "name": "Guinea-Bisáu", "iso2": "GW", "iso3": "GNB" },
            { "name": "Guinea Ecuatorial", "iso2": "GQ", "iso3": "GNQ" },
            { "name": "Guyana", "iso2": "GY", "iso3": "GUY" },
            { "name": "Haití", "iso2": "HT", "iso3": "HTI" },
            { "name": "Honduras", "iso2": "HN", "iso3": "HND" },
            { "name": "Hungría", "iso2": "HU", "iso3": "HUN" },
            { "name": "India", "iso2": "IN", "iso3": "IND" },
            { "name": "Indonesia", "iso2": "ID", "iso3": "IDN" },
            { "name": "Irak", "iso2": "IQ", "iso3": "IRQ" },
            { "name": "Irán", "iso2": "IR", "iso3": "IRN" },
            { "name": "Irlanda", "iso2": "IE", "iso3": "IRL" },
            { "name": "Islandia", "iso2": "IS", "iso3": "ISL" },
            { "name": "Israel", "iso2": "IL", "iso3": "ISR" },
            { "name": "Italia", "iso2": "IT", "iso3": "ITA" },
            { "name": "Jamaica", "iso2": "JM", "iso3": "JAM" },
            { "name": "Japón", "iso2": "JP", "iso3": "JPN" },
            { "name": "Jordania", "iso2": "JO", "iso3": "JOR" },
            { "name": "Kazajistán", "iso2": "KZ", "iso3": "KAZ" },
            { "name": "Kenia", "iso2": "KE", "iso3": "KEN" },
            { "name": "Kirguistán", "iso2": "KG", "iso3": "KGZ" },
            { "name": "Kiribati", "iso2": "KI", "iso3": "KIR" },
            { "name": "Kuwait", "iso2": "KW", "iso3": "KWT" },
            { "name": "Laos", "iso2": "LA", "iso3": "LAO" },
            { "name": "Lesoto", "iso2": "LS", "iso3": "LSO" },
            { "name": "Letonia", "iso2": "LV", "iso3": "LVA" },
            { "name": "Líbano", "iso2": "LB", "iso3": "LBN" },
            { "name": "Liberia", "iso2": "LR", "iso3": "LBR" },
            { "name": "Libia", "iso2": "LY", "iso3": "LBY" },
            { "name": "Liechtenstein", "iso2": "LI", "iso3": "LIE" },
            { "name": "Lituania", "iso2": "LT", "iso3": "LTU" },
            { "name": "Luxemburgo", "iso2": "LU", "iso3": "LUX" },
            { "name": "Madagascar", "iso2": "MG", "iso3": "MDG" },
            { "name": "Malasia", "iso2": "MY", "iso3": "MYS" },
            { "name": "Malaui", "iso2": "MW", "iso3": "MWI" },
            { "name": "Maldivas", "iso2": "MV", "iso3": "MDV" },
            { "name": "Malí", "iso2": "ML", "iso3": "MLI" },
            { "name": "Malta", "iso2": "MT", "iso3": "MLT" },
            { "name": "Marruecos", "iso2": "MA", "iso3": "MAR" },
            { "name": "Mauricio", "iso2": "MU", "iso3": "MUS" },
            { "name": "Mauritania", "iso2": "MR", "iso3": "MRT" },
            { "name": "México", "iso2": "MX", "iso3": "MEX" },
            { "name": "Micronesia", "iso2": "FM", "iso3": "FSM" },
            { "name": "Moldavia", "iso2": "MD", "iso3": "MDA" },
            { "name": "Mónaco", "iso2": "MC", "iso3": "MCO" },
            { "name": "Mongolia", "iso2": "MN", "iso3": "MNG" },
            { "name": "Montenegro", "iso2": "ME", "iso3": "MNE" },
            { "name": "Mozambique", "iso2": "MZ", "iso3": "MOZ" },
            { "name": "Myanmar", "iso2": "MM", "iso3": "MMR" },
            { "name": "Namibia", "iso2": "NA", "iso3": "NAM" },
            { "name": "Nauru", "iso2": "NR", "iso3": "NRU" },
            { "name": "Nepal", "iso2": "NP", "iso3": "NPL" },
            { "name": "Nicaragua", "iso2": "NI", "iso3": "NIC" },
            { "name": "Níger", "iso2": "NE", "iso3": "NER" },
            { "name": "Nigeria", "iso2": "NG", "iso3": "NGA" },
            { "name": "Noruega", "iso2": "NO", "iso3": "NOR" },
            { "name": "Nueva Zelanda", "iso2": "NZ", "iso3": "NZL" },
            { "name": "Omán", "iso2": "OM", "iso3": "OMN" },
            { "name": "Países Bajos", "iso2": "NL", "iso3": "NLD" },
            { "name": "Pakistán", "iso2": "PK", "iso3": "PAK" },
            { "name": "Palaos", "iso2": "PW", "iso3": "PLW" },
            { "name": "Panamá", "iso2": "PA", "iso3": "PAN" },
            { "name": "Papúa Nueva Guinea", "iso2": "PG", "iso3": "PNG" },
            { "name": "Paraguay", "iso2": "PY", "iso3": "PRY" },
            { "name": "Perú", "iso2": "PE", "iso3": "PER" },
            { "name": "Polonia", "iso2": "PL", "iso3": "POL" },
            { "name": "Portugal", "iso2": "PT", "iso3": "PRT" },
            { "name": "Reino Unido", "iso2": "GB", "iso3": "GBR" },
            { "name": "República Centroafricana", "iso2": "CF", "iso3": "CAF" },
            { "name": "República Checa", "iso2": "CZ", "iso3": "CZE" },
            { "name": "República Dominicana", "iso2": "DO", "iso3": "DOM" },
            { "name": "Ruanda", "iso2": "RW", "iso3": "RWA" },
            { "name": "Rumanía", "iso2": "RO", "iso3": "ROU" },
            { "name": "Rusia", "iso2": "RU", "iso3": "RUS" },
            { "name": "Samoa", "iso2": "WS", "iso3": "WSM" },
            { "name": "San Cristóbal y Nieves", "iso2": "KN", "iso3": "KNA" },
            { "name": "San Marino", "iso2": "SM", "iso3": "SMR" },
            { "name": "San Vicente y las Granadinas", "iso2": "VC", "iso3": "VCT" },
            { "name": "Santa Lucía", "iso2": "LC", "iso3": "LCA" },
            { "name": "Santo Tomé y Príncipe", "iso2": "ST", "iso3": "STP" },
            { "name": "Senegal", "iso2": "SN", "iso3": "SEN" },
            { "name": "Serbia", "iso2": "RS", "iso3": "SRB" },
            { "name": "Seychelles", "iso2": "SC", "iso3": "SYC" },
            { "name": "Sierra Leona", "iso2": "SL", "iso3": "SLE" },
            { "name": "Singapur", "iso2": "SG", "iso3": "SGP" },
            { "name": "Siria", "iso2": "SY", "iso3": "SYR" },
            { "name": "Somalia", "iso2": "SO", "iso3": "SOM" },
            { "name": "Sri Lanka", "iso2": "LK", "iso3": "LKA" },
            { "name": "Sudáfrica", "iso2": "ZA", "iso3": "ZAF" },
            { "name": "Sudán", "iso2": "SD", "iso3": "SDN" },
            { "name": "Sudán del Sur", "iso2": "SS", "iso3": "SSD" },
            { "name": "Suecia", "iso2": "SE", "iso3": "SWE" },
            { "name": "Suiza", "iso2": "CH", "iso3": "CHE" },
            { "name": "Surinam", "iso2": "SR", "iso3": "SUR" },
            { "name": "Tailandia", "iso2": "TH", "iso3": "THA" },
            { "name": "Tanzania", "iso2": "TZ", "iso3": "TZA" },
            { "name": "Tayikistán", "iso2": "TJ", "iso3": "TJK" },
            { "name": "Timor Oriental", "iso2": "TL", "iso3": "TLS" },
            { "name": "Togo", "iso2": "TG", "iso3": "TGO" },
            { "name": "Tonga", "iso2": "TO", "iso3": "TON" },
            { "name": "Trinidad y Tobago", "iso2": "TT", "iso3": "TTO" },
            { "name": "Túnez", "iso2": "TN", "iso3": "TUN" },
            { "name": "Turkmenistán", "iso2": "TM", "iso3": "TKM" },
            { "name": "Turquía", "iso2": "TR", "iso3": "TUR" },
            { "name": "Tuvalu", "iso2": "TV", "iso3": "TUV" },
            { "name": "Ucrania", "iso2": "UA", "iso3": "UKR" },
            { "name": "Uganda", "iso2": "UG", "iso3": "UGA" },
            { "name": "Uruguay", "iso2": "UY", "iso3": "URY" },
            { "name": "Uzbekistán", "iso2": "UZ", "iso3": "UZB" },
            { "name": "Vanuatu", "iso2": "VU", "iso3": "VUT" },
            { "name": "Venezuela", "iso2": "VE", "iso3": "VEN" },
            { "name": "Vietnam", "iso2": "VN", "iso3": "VNM" },
            { "name": "Yemen", "iso2": "YE", "iso3": "YEM" },
            { "name": "Yibuti", "iso2": "DJ", "iso3": "DJI" },
            { "name": "Zambia", "iso2": "ZM", "iso3": "ZMB" },
            { "name": "Zimbabue", "iso2": "ZW", "iso3": "ZWE" }
            ]

        if db.query(Country).count() == 0:
            for country in countries:
                db.add(Country(name=country["name"], iso_2_code=country["iso2"], iso_3_code=country["iso3"]))
                db.commit()
            print("[countries] Table seeded successfully✅ ")
        else:
            print("[countries] Table already seeded")
            
    @staticmethod
    def truncate(db: Session):
        db.query(Country).delete()
        db.commit()
        print("[countries] Table truncated successfully✅ ")