"""create companies table

Revision ID: 248d163bd88d
Revises: 648a56b7c63f
Create Date: 2025-05-29 10:25:03.066046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248d163bd88d'
down_revision: Union[str, None] = '648a56b7c63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('legal_name', sa.String(length=40), nullable=False),
    sa.Column('trade_name', sa.String(length=40), nullable=False),
    sa.Column('cif', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.BIGINT(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('fax', sa.String(length=15), nullable=True),
    sa.Column('web', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cif'), 'companies', ['cif'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.drop_index('name', table_name='permissions')
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_index('name', 'permissions', ['name'], unique=True)
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_cif'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
