"""iso code fields to countries table and postcode to provinces table

Revision ID: 648a56b7c63f
Revises: 6fb065ba1c4d
Create Date: 2025-05-29 08:24:21.543274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '648a56b7c63f'
down_revision: Union[str, None] = '6fb065ba1c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('iso_2_code', sa.String(length=2), nullable=False))
    op.add_column('countries', sa.Column('iso_3_code', sa.String(length=3), nullable=False))
    op.create_unique_constraint('uq_countries_iso_2_code', 'countries', ['iso_2_code'])
    op.create_unique_constraint('uq_countries_iso_3_code', 'countries', ['iso_3_code'])
    op.add_column('provinces', sa.Column('postcode', sa.String(length=5), nullable=False))
    op.alter_column('provinces', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index('name', table_name='provinces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provinces', 'name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('provinces', 'postcode')
    op.drop_constraint('uq_countries_iso_3_code', 'countries', type_='unique')
    op.drop_constraint('uq_countries_iso_2_code', 'countries', type_='unique')
    op.drop_column('countries', 'iso_3_code')
    op.drop_column('countries', 'iso_2_code')
    # ### end Alembic commands ###
