"""deleted fax column in companies

Revision ID: 773e729bbbca
Revises: 9e0aa321bb0f
Create Date: 2025-06-06 12:51:00.681776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '773e729bbbca'
down_revision: Union[str, None] = '9e0aa321bb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'fax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('fax', mysql.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
