"""unique legal name and trade name

Revision ID: 9e0aa321bb0f
Revises: 248d163bd88d
Create Date: 2025-05-30 10:41:25.557179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0aa321bb0f'
down_revision: Union[str, None] = '248d163bd88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_legal_name'), 'companies', ['legal_name'], unique=True)
    op.create_index(op.f('ix_companies_trade_name'), 'companies', ['trade_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_trade_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    # ### end Alembic commands ###
